spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: blog-command-service
  datasource:
    url: jdbc:mysql://3.80.230.96/USER_BLOG_DB?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      properties:
        hibernate:
          format_sql: true

  # 로깅 설정
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  # 서버 설정
server:
  port: 8085

cloud:
  aws:
    s3:
      bucket: suhabuckettest
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
# port: 0

eureka:
  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.213.139.105:8761/eureka

env :
  user-feign-url: http://44.201.129.31:8084/api/users/feign
  category-feign-url : http://54.147.162.65:8086/api/category/feign
  theme-feign-url :  http://54.147.162.65:8086/api/theme/feign
  file-command-feign-url :  http://3.86.230.148:8087/api/feign
